import = ["~/.config/alacritty/themes/alacritty-theme/themes/tokyo-night.toml"]

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001v"
key = "T"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001c"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001k"
key = "K"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001j"
key = "J"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001t"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0001n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001p"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = """
\u0001:clear
"""
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mode = "Vi"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
opacity = 0.999

[font.normal]
family = "0xProto Nerd Font"
